sajari/sdk-react

- src/controllers/analytics/ga.ts
- src/global.d.ts
Adds support for [gtag.js](https://developers.google.com/analytics/devguides/collection/gtagjs/).
@mish15 added you to this, as was a little confused by the analytics events we are sending. Is there are reason we are sending page views for search events, and not [search events](https://developers.google.com/analytics/devguides/collection/gtagjs/events) themselves?
I'm also not 100% across google analytics so just wanted to make sure I hadn't messed something up in the process of add the gtag support.
> controllers/analytics: add support for gtag analytics

- .babelrc
- package.json
- src/components/Input/Input.tsx
- src/components/Input/Results.tsx
- src/components/Input/Suggestions.tsx
- src/components/Input/Typeahead.tsx
- src/components/Input/shared/Dropdown.tsx
- src/components/Paginator/Paginator.tsx
- src/components/Result/Image.tsx
- src/components/Result/Result.tsx
- src/components/Tabs/Tab/Tab.tsx
- src/docs/wrapper.tsx
- yarn.lock
**WHAT**
Unable to compile styles of components after running `build` due to `TypeScript` (https://github.com/emotion-js/emotion/issues/1046)
```
<div css={styles} />
```
will be compiled to
```
<div css="[object Object]"></div>
```
**HOW**
Add jsx pragma on top of each component to get styles compiled
```
/** @jsx jsx */ jsx;
import { jsx } from "@emotion/core";
```
> Fix emotion10 fail to compile

- src/components/Tabs/Tab/Tab.tsx
This PR aims to resolve https://github.com/sajari/website-search-integration/issues/13
WHAT: 
Cannot use `tab` key to move focus on the tab button.
WHY:
Because of using `div` as the markup for tab buttons, the tag doesn't behave like the native `button`.
HOW:
Add `role` & `tab-index` attrs to let browsers identify tab buttons as a native button.
Add `keydown` event to preserve the click action by pressing `Enter` or `Space`.
> Tab: allow using keyboard to select tab

- package.json
- src/components/Input/Input.tsx
- src/components/Input/Typeahead.tsx
This PR aims to resolve https://github.com/sajari/website-search-integration/issues/11
WHAT:
It's hard for users to click + drag to select the text on the search box.
WHY:
The input was wrapped by `React-Autosize-Input` component in order to position . This implementation made the width of the input not span over its div container so users will actually click + drag on the div container rather than the input.
HOW:
- Remove the `React-Autosize-Input` component and force the width of the input to span over its parent box. 
- Keep the typeahead word without trimming, place it on the left-most of the search box and vertically center it. Finally, hide the substring of the actual input by `opacity:0`.
Here is the demo - https://codesandbox.io/s/8804qlkr02.
> Input: fix hard to click drag to select text

- src/components/Search/Search.tsx
- src/components/Search/utils.ts
**WHAT**:
I am using the `Search` component to build the interface for #102 but the UI requires data like `totalResults`, `q.original`, etc and I have to use `Consumer` to get these data.
**WHY**:
It's cumbersome to write nested render-prop components since we can do an update to use just `Search` only.
**HOW**:
Get all the needed data from `pipeline` methods like `getResults ` or `getResponse` and inject those to `summary` prop and pass to render prop function.
> Search: wrap summary data to Search component

- src/components/Input/Input.tsx
- src/components/Search/Search.tsx
- src/components/context/pipeline/Provider.tsx
**WHAT**:
when the user presses Tab and comes on the search box, a "No Results" prompt appears for the Voiceover utility
**WHY**:
~Because the downshift `getA11yStatusMessage` function will return "No results." if the list of items is empty - https://github.com/downshift-js/downshift#geta11ystatusmessage~
When input is focused, it will trigger `openmenu` which will call `getA11yStatusMessage`. Initially, there is no search results so the status message will be `no results` which will be called out by screen reader.
**HOW**:
~Passing a function to return empty string to disable the behavior (have tested and screen reader still works properly on suggestion dropdown)~
Checking to call `openmenu` only when at least one result is available.
> fix select Input returns No Results prompt

- src/components/Paginator/Paginator.tsx
Add type attr to the previous page button
> fix(paginator): add missing "type" attribute

- src/components/RangeSlider/RangeSlider.tsx
- src/components/RangeSlider/RangeSliderUI.tsx
- src/controllers/aggregateFilter.ts
- src/controllers/index.ts
- src/controllers/rangeAggregateFilter.ts
- src/controllers/rangeAggregrateFilter.ts
- src/controllers/rangeFilter.ts
- src/index.ts
- yarn.lock
This PR aims to make improvements in performance and usability of the `rangeAggregrateFilter` and its UI wrapper `RangeAggregrateSlider`:
- put `filter.set` inside a denounce to limit the number of search call
- hide the slider if the `min` and `max` are equal
- auto join `field` value into `min` and `max` property of `Value` object
- remove unused `multi` field from `rangeAggregrateFilter` constructor
> improve range slider filter

- src/components/Result/Image.tsx
**What**: there is 404 error warning in case a record doesn't have a preview image
**Why**: in case `src` is undefined, we still use it as the value for `background-image`
**How**: check only adding `background-image` if the `src` does exist
> components/result: fix 404 warning due to undefined image

- src/components/Input/Input.tsx
**WHAT**: broken ARIA reference warning
**WHY**:  `aria-labelledby` is injected to the parent div via `getRootProps` but the include doesn't have a label with the `getLabelProps` spreading.
**HOW**: since we've already defined `aria-label` for the input, just need to omit `aria-labelledby` from being added by `getRootProps`.
> components/input: fix aria-labelledby reference warning

- docs/pages/hooks/usepagesize.mdx
- packages/hooks/src/usePageSize/index.ts
Initially `usePageSize` composed `usePagination` - particularly `pageSize` variable - but since that value in `usePagination` is derived from the `response` which is only updated between search request so it doesn't make sense as page size is something user can update client-side and as a result changes to `pageSize` from `usePageSize` cannot be picked up by React.
> V3: fix: pageSize not reactive

- docs/components/SearchProvider.tsx
- docs/pages/hooks/usepagesize.mdx
- example/index.tsx
- packages/hooks/src/SearchContextProvider/index.tsx
- packages/hooks/src/SearchContextProvider/types.ts
- packages/hooks/src/index.ts
- packages/hooks/src/useSearch/index.ts
- packages/hooks/src/utils/mapResultFields.ts
- packages/hooks/src/utils/test/mapResultFields.test.ts
- packages/search-ui/src/Results/index.tsx
```js
{
category: ["level3", "level2", "level1"]
/**
*  ^ This will lookup "level3" field in 
* the response object and if it's not found then fallback to lookup "level2" and so forth
*/
}
```
```js
{
url: "`/products/${slug}`"
/**
* ^ `slug` is a field in the response object, note the backticks
*/
}
```
```js
{
category: (data) => data.level3 || data.level2 || data.level1 || "Unknown"
}
```
It also support function's body as a string:
```js
{
category: "!function return 'Phone'"
/**
* ^ Note the `!function`
*/
}
```
> V3: chore: improve field mapping

- docs/pages/hooks/usepagesize.mdx
- docs/pages/hooks/usepagination.mdx
- docs/pages/hooks/usesearch.mdx
- docs/pages/hooks/usesorting.mdx
- docs/pages/search-ui/pagesize.mdx
- docs/pages/search-ui/pagination.mdx
- docs/pages/search-ui/sorting.mdx
- packages/hooks/src/SearchContextProvider/controllers/pipeline.ts
- packages/hooks/src/SearchContextProvider/index.tsx
- packages/hooks/src/SearchContextProvider/types.ts
- packages/hooks/src/useSearch/index.ts
- packages/hooks/src/useSearch/types.ts
- packages/hooks/src/utils/debounce.ts
- packages/search-ui/src/PageSize/index.tsx
- packages/search-ui/src/PageSize/types.ts
- packages/search-ui/src/Sorting/index.tsx
- packages/search-ui/src/Sorting/types.ts
Rewrite the `useSearch` to be able to search when the request object changes
It should be noted that when this PR is merged all hooks change will trigger search request
> V3: refactor: rewrite useSearch hook

- packages/hooks/src/useSearch/index.ts
> V3: chore: simplify useSearch logic

- packages/hooks/src/useSearchContext/index.ts
- packages/search-ui/src/Summary/index.tsx
> V3: fix: summary logic

- packages/hooks/src/SearchContextProvider/index.tsx
- packages/hooks/src/utils/assertion.ts
> V3: fix: search on empty string with custom filter

- packages/components/src/Swatch/color.tsx
- packages/hooks/src/SearchContextProvider/index.tsx
- packages/hooks/src/utils/assertion.ts
> V3: fix: convert Swatch to be controlled input

- packages/components/src/Swatch/color.tsx
- packages/components/src/hooks/useRingStyles.ts
- packages/styles/src/styled/theming.tsx
Casting `ThemeFn` to `string`, otherwise, it gives the warning causing build failed.
> fix: twTheme warning

- packages/utils/package.json
@sampotts All the `1.0.0-alpha.1` packages work great, the fresh CRA is able to compile normally.
Just need this PR sorted out so that I won't have to manually add `@emotion/core` and etc when installing `@sajari/react-components` (which uses `utils` internally)
> V3: fix: utils - specify emotion as deps instead of devdeps

- docs/pages/hooks/usepagesize.mdx
- docs/pages/hooks/usepagination.mdx
- docs/pages/hooks/usesorting.mdx
- docs/pages/search-ui/pagesize.mdx
- docs/pages/search-ui/sorting.mdx
- docs/pages/tracking/clicktracking.mdx
- docs/pages/tracking/notracking.mdx
- docs/pages/tracking/posnegtracking.mdx
- packages/hooks/src/SearchContextProvider/index.tsx
- packages/hooks/src/SearchContextProvider/types.ts
- packages/hooks/src/usePageSize/index.ts
- packages/hooks/src/useQuery/index.ts
- packages/hooks/src/useSearch/index.ts
- packages/hooks/src/useSorting/index.ts
Currently, when we select any filter option, 2 requests are sent, 1 is from the `"selection-updated"` event handler that directly invokes the search function, and 2 is from `useSearch`'s logic of running effect whenever the value object changes.
This case isn't ideal and there is a potential of a loop occurring, the search function sets the values object -> which are picked up by `useEffect` -> which again runs the search function
Before the change, `useFilter` section of the docs when rendered will fire more than 3 requests which doesn't add up with the number of examples, and choosing any filter fires 2 requests as said above
After the change, only 3 requests are fired on mount, and only 1 request for each action after (input, filter)
@sampotts if you can please do a sanity check again …
> V3: chore: tidy up search logic

- docs/pages/hooks/usefilter.mdx
- docs/pages/search-ui/filter.mdx
- packages/components/package.json
- packages/hooks/src/SearchContextProvider/controllers/filters/Filter.ts
- packages/hooks/src/SearchContextProvider/controllers/filters/types.ts
- packages/hooks/src/useFilter/index.ts
- packages/search-ui/src/Filter/ListFilter.tsx
- packages/search-ui/src/Filter/types.ts
- packages/search-ui/src/Filter/utils.ts
This change adds several props to the `Filter` component: 
- `sort` which allows choosing how the filter is sorted (`'count'` (by the numeric count), `'alpha'` (using the label) or `'none'` (random order))
- `sortAscending` - default `true` if sort is not `'count'`
- `pinSelected` - pin selected options to the top of the list - default `true` 
It changes `multi` and `count` to true in the `Filter` Class by default since I think this would be the most common use-case. 
It also renames `repeated` to `array` to match the latest API naming changes.
> v3: feat: updated props for Filter component

- docs/components/components.ts
- docs/pages/hooks/useautocomplete.mdx
- docs/pages/search-ui/summary.mdx
- packages/hooks/src/index.ts
- packages/hooks/src/useAutocomplete/index.ts
- packages/search-ui/src/Summary/index.tsx
- packages/search-ui/src/Summary/types.ts
> V3: chore: add query overriding feature to Summary

- docs/pages/hooks/usefilter.mdx
- docs/pages/hooks/usepagination.mdx
- docs/pages/hooks/usesorting.mdx
- docs/pages/search-ui/filter.mdx
- docs/pages/search-ui/input.mdx
- docs/pages/search-ui/pagesize.mdx
- docs/pages/search-ui/sorting.mdx
- docs/pages/search-ui/summary.mdx
- docs/pages/tracking/clicktracking.mdx
- docs/pages/tracking/notracking.mdx
- docs/pages/tracking/posnegtracking.mdx
- package.json
- packages/components/src/Box/index.tsx
- packages/components/src/Box/types.ts
- packages/components/src/Combobox/index.tsx
- packages/components/src/index.ts
- packages/hooks/src/useSorting/index.ts
- packages/search-ui/src/Input/index.tsx
- packages/search-ui/src/Results/index.tsx
- packages/search-ui/src/Results/types.ts
The change aims to fix the issue as when typing in the Input composition in `standard` mode will cause the error `TypeError: n.startsWith is not a function`.
This PR also includes the update to make sure the examples from docs compatible with the previous changes from Input composition.
> V3: fix Input standard mode broken when typing in

- docs/pages/search-ui/input.mdx
- packages/search-ui/src/Input/index.tsx
- packages/search-ui/src/Input/types.ts
> V3: add mode to input

- packages/hooks/src/SearchContextProvider/index.tsx
- packages/hooks/src/useAutocomplete/index.ts
An oversight on my end, the `searching` state is modified even if it's just instant searching, there should be a separate state for it as well.
> V3: fix searching state

- docs/pages/search-ui/viewtype.mdx
- packages/hooks/src/SearchContextProvider/index.tsx
- packages/hooks/src/SearchContextProvider/types.ts
- packages/hooks/src/useSearchContext/index.ts
- packages/search-ui/src/Results/index.tsx
- packages/search-ui/src/ViewType/index.tsx
- packages/search-ui/src/ViewType/types.ts
> V3: set viewtype in context

- packages/search-ui/src/Results/index.tsx
- packages/search-ui/src/Results/styles.ts
> V3: fix results grid view

- packages/hooks/src/SearchContextProvider/controllers/variables.ts
When `searchOnLoad` is specified, it didn't seem to send any search request but in fact it did, it's just that the result came back as empty because the filter `_id != ""` was not present, read below on how this PR addresses that issue.
> V3: fix search on load

- docs/pages/search-ui/input.mdx
- packages/components/src/Combobox/components/DropdownItem/index.tsx
- packages/components/src/Combobox/context.tsx
- packages/components/src/Combobox/index.tsx
- packages/search-ui/src/Input/index.tsx
Resolve some issues related to Input component:
> V3: fix enter key not trigger search using Input component

- packages/search-ui/src/Filter/ListFilter.tsx
- packages/search-ui/src/Filter/types.ts
Use `Combobox` instead of `Input` in `Filter` component to fix the issue when a search is unexpectedly triggered if we type in the search box in a filter list.
> V3:  fix wrong use of Input component in Filter

- packages/hooks/src/SearchContextProvider/index.tsx
This PR aims to fix the issue when changing filter, query, sorting or page size does not reset to page 1.
> V3: fix not reset to page 1 if query variables changed

- packages/components/src/Combobox/components/DropdownItem/styles.ts
- packages/components/src/Combobox/components/DropdownResult/index.tsx
- packages/components/src/Combobox/components/DropdownResult/styles.ts
- packages/components/src/Label/styles.ts
- packages/components/src/Tabs/TabList/styles.ts
- packages/search-ui/src/Results/components/Result/styles.ts
- packages/utils/src/styles/index.ts
Use the power of generic to retain the keys of `styles` object for the output of `mapStyles` function for better code autocompletion and let TS keep an eye on `undefined` check.
Before:
After:
> V3: improve key mapping for mapStyles util

- packages/search-ui/src/ContextProvider/types.ts
- packages/search-ui/src/PageSize/index.tsx
- packages/search-ui/src/PageSize/styles.ts
- packages/search-ui/src/PageSize/types.ts
Add options to control styles for PageSize component:
> V3: add option to control styles for page size

- docs/pages/hooks/useautocomplete.mdx
> V3: add onSelect handler to useAutocomplete docs

- packages/components/src/Swatch/color.tsx
- packages/components/src/Swatch/index.tsx
- packages/components/src/Swatch/styles.tsx
- packages/components/src/Swatch/types.ts
- packages/components/src/hooks/index.ts
- packages/components/src/hooks/useBorderRadius.ts
Add options to control styles for Swatch component:
> V3: add option to control styles for Swatch

- packages/search-ui/src/Filter/RatingFilter.tsx
`ListFilter` is rerendering multiple times because of anonymous function `itemRender` -> poor performance.
> V3: rating filter improvement

- jest.config.base.js
- package.json
- packages/components/src/Swatch/color.tsx
- packages/components/src/Swatch/test/Swatch.test.tsx
- packages/components/src/Swatch/types.ts
- yarn.lock
> V3: add test for Swatch

- docs/pages/components/image.mdx
- packages/components/src/Image/index.tsx
- packages/components/src/Image/types.ts
- packages/components/src/Image/useImageStyles.ts
There is a particular weird bug where specifying `src` as an array results in images not loading despite having correct `src` attributes, hence the `hoverSrc` prop.
Also I think changing the type of `src` would potentially break current consumer of the sdk's code.
As for the changes to fields mapping, I've not seen any search results that have 2 images so I'll need to test that out first.
P.S: naming is hard so if you have anything better than `hoverSrc` feel free to throw it up here!
> V3: add hover functionality to image

- yarn.lock
This includes the update to the new token URL.
> update @sajari/sdk-js to v1.0.11

- .changeset/config.json
Fix release action run failed due to providing a wrong config setting for `changesets` - https://github.com/sajari/sdk-react/runs/1668436313?check_suite_focus=true
> fix: release action run failed

- .changeset/itchy-mirrors-roll.md
- packages/hooks/src/ContextProvider/index.tsx
- packages/hooks/src/ContextProvider/types.ts
- packages/hooks/src/useSearchContext/index.ts
- packages/search-ui/src/ContextProvider/index.tsx
- packages/search-ui/src/ContextProvider/types.ts
- packages/search-ui/src/Results/index.tsx
- packages/search-ui/src/ViewType/index.tsx
Add the option to set a default value for `viewType`. Also, moved viewType state from `hooks` package to `search-ui` package so leaving the hooks to only be in charge of handling data from the backend.
> feat: support setting default value for viewType

- .changeset/fuzzy-horses-hang.md
- docs/pages/components/select.mdx
- packages/components/src/Tabs/Tab/styles.ts
- packages/search-ui/src/Filter/ListFilter.tsx
This fix prevents the following error:
> fix: improve query selector syntax

- .changeset/breezy-ties-argue.md
- packages/components/src/hooks/useVoiceInput.ts
Currently, we only support the prefixed `webkitSpeechRecognition`. This change adds support for the unprefixed version. Apparently, support is coming in the new version of Safari. 
https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition
> fix: support unprefixed SpeechRecognition

- .changeset/curvy-cows-retire.md
- packages/utils/src/object.ts
- packages/utils/src/test/object.test.ts
This change adds the ability to specify how arrays are merged. Currently, the options are:
* `'concat'` - Concatenate arrays.
* `'union'` - Union arrays, skipping items that already exist.
* `'replace'` - Replace all array items.
> utils: add MergeOptions for merge util

- .changeset/sweet-ants-roll.md
- packages/hooks/src/useSearchContext/index.ts
export `clear` method in the return of useSearchContext so that it can be used to reset the response.
> fix: make clear method public in useSearchContext

- .changeset/tidy-clouds-press.md
- packages/components/src/Combobox/index.tsx
Fix the issue raised internally by the team [here](https://sajari.atlassian.net/browse/SF-250). A similar issue was raised and fixed in https://github.com/downshift-js/downshift/issues/1108.
> fix: typing mid query snaps to the end of the query

- .changeset/polite-cups-remember.md
- packages/hooks/src/ContextProvider/controllers/filters/FilterBuilder.ts
- packages/hooks/src/ContextProvider/controllers/filters/test/FilterBuilder.test.ts
- packages/hooks/src/ContextProvider/controllers/filters/utils.ts
**WHAT**:
If you set a price filter along with another filter (e.g. `product_type`) in the Shopify UI to a range where it returns no results, then you reset the price range, it returns all results rather than just the results for the other filter.
**WHY**:
Take the possible scenario:
- Step 1: search query "hello" with a range filter of field `price` and list filter of field `category`. This will respond 999 items and aggregate options for `category` is `[A, B, C]`.
- Step 2: select the option `A` will respond 100 items.
- Step 3: select the range `[x, y]` for the `price` will respond 9 items and the new aggregate options is `[B]`.
- Step 4: reset the price range will respond 999 items instead of 100.
It's because the current implementation of `filter()` method will ignore the value which …
> fix: resetting range filter ignores other filters

- .changeset/violet-ways-knock.md
- packages/components/src/Tabs/TabList/index.tsx
**WHAT**:
Sometimes, clicking on a tab shows no response. See the video for details:
https://user-images.githubusercontent.com/12707960/108721944-25b1a080-7555-11eb-867a-c3eeef1235a5.mov
**WHY**:
The node param from ref callback sometimes gets `null` (not yet found out why) so calling `.focus` on a `null` object will cause the error and block the UI.
```jsx
return cloneElement(child, {
ref: (node: HTMLElement) => {
allNodes.current[index] = node;
return node;
},
```
**HOW**:
Prevent the issue by checking `null` before calling `.focus`. Note that, it is a workaround solution because the focus function could be broken instead.
> fix: tab sometimes unclickable

- .changeset/tender-masks-behave.md
- packages/hooks/src/useRangeFilter/index.ts
Fix the issue when using the range filter will sometimes cause mismatches between the UI and the response. Previously, the attempt was to retain the previous range values once a new request was made, but it is tricky and often leads to the issues mentioned earlier. The change aims to simplify the logic:
- Only update the `min` and `max` from the response if the query was changed.
- Once the `min` and `max` changed, set the range to `[min, max]`.
Internal issues:
- https://sajari.atlassian.net/browse/SF-254
- https://sajari.atlassian.net/browse/SF-251
> fix: simplify useRangeFilter logic to avoid incorrect response bugs

- .changeset/cuddly-turkeys-film.md
- packages/hooks/src/ContextProvider/controllers/filters/RangeFilterBuilder.ts
- packages/hooks/src/useRangeFilter/index.ts
Added support `frozen` state for `RangeFilterBuilder`. If `frozen` is `true`, blocking any update for `min`, `max` or `range`. This is the prerequisite of https://github.com/sajari/search-widgets/pull/16.
> feat: add support frozen state for RangeFilterBuilder

- .changeset/five-coins-bow.md
- .changeset/warm-scissors-wash.md
- packages/components/src/Combobox/index.tsx
@sampotts Sorry I think the relative positioning should have been here instead of in the widgets.
> fix: add relative position for input container

- .changeset/calm-laws-hammer.md
- packages/search-ui/src/Filter/RatingFilter.tsx
At the moment the ratings filter component options can only be ordered from 1 star to 5 stars but it makes more sense to order it from 5 stars to 1 star like Amazon do.
**Before**:
**After**:
This resolved the [internal issue](https://sajari.atlassian.net/browse/SF-296).
> fix: sort rating options from highest to lowest

- .changeset/five-waves-press.md
- packages/components/src/Combobox/index.tsx
- packages/search-ui/src/Input/index.tsx
- packages/search-ui/src/Input/types.ts
Fix the issue when using speech search does not trigger a search for the voice input. Also, make an update to open the dropdown menu if the input mode is `results`.
**Standard mode**
https://user-images.githubusercontent.com/12707960/112083180-29b6f980-8bb9-11eb-948a-367808266a11.mov
**Results mode**
https://user-images.githubusercontent.com/12707960/112082668-56b6dc80-8bb8-11eb-98ca-4227b5e39abd.mov
> fix: voice input not trigger search

- .changeset/five-hats-sparkle.md
- packages/search-ui/src/Input/index.tsx
- packages/search-ui/src/Input/types.ts
Fix the issue when passing `className` for `Input` does not work if the `customClassNames` is set in the context.
> fix: className of Input being overridden by context customClassNames

- .changeset/moody-colts-happen.md
- packages/components/src/Modal/styles.ts
- packages/utils/src/styles/tailwind.config.js
Increase the `z-index` value of `Modal` to 10000 to somewhat avoid it being overlapped by other elements.
> fix: modal being overlapped by elements having higher z-index

- .changeset/spicy-lies-impress.md
- packages/components/src/Combobox/styles.ts
Add additional styling for `Combobox`'s input to somewhat avoid its styles being overridden by external CSS. This issue was spotted on https://jp2x4e97xnpvihev-26763868.shopifypreview.com/search?q=hello&viewType=list as the input looks off due to a margin issue.
**Before**:
**After**:
Note that this is a partial fix to avoid the strange styling issue. If the styling looks crash, we should consider using `importantStyles` in the Context - https://react.docs.sajari.com/styling#important-styles.
> fix: input style being overridden by theme CSS

- .changeset/sixty-numbers-vanish.md
- docs/pages/search-ui/filter.mdx
- packages/search-ui/src/Filter/ListFilter.tsx
- packages/search-ui/src/Filter/RatingFilter.tsx
- packages/search-ui/src/Filter/SelectFilter.tsx
- packages/search-ui/src/Filter/TabFilter.tsx
- packages/search-ui/src/Filter/types.ts
Add option to hide records count on filter components.
**Default**:
**With `hideCount`**:
> feat: add option to hide records count

- .changeset/curvy-pets-rule.md
- packages/search-ui/src/Filter/test/utils.test.ts
- packages/search-ui/src/Filter/utils.ts
This issue was noticed in the integration builder as `undefined` text is displayed if the option text is an empty string.
> fix: formatLabel returns undefined for empty string

- .changeset/unlucky-suns-drive.md
- packages/search-ui/src/Input/types.ts
Enable `showPoweredBy` prop for Input to show/hide Sajari logo.
> fix: missing showPoweredBy prop in Input

- .changeset/tough-pets-hope.md
- packages/components/src/Button/styles.ts
- packages/components/src/Button/test/__snapshots__/Button.test.tsx.snap
- packages/components/src/ButtonGroup/test/__snapshots__/ButtonGroup.test.tsx.snap
- packages/components/src/Checkbox/styles.ts
- packages/components/src/Label/styles.ts
- packages/components/src/Radio/styles.ts
- packages/components/src/RangeInput/components/Handle/styles.ts
- packages/components/src/Select/components/Button/styles.ts
Prevent styling of components from being overridden by external CSS such as Shopify themes. Mostly, issues come from the box model properties and background and text color in focus and hover state.
> fix: styling being overridden by external CSS

- .changeset/soft-cameras-brush.md
- packages/components/src/Combobox/index.tsx
The `onKeyDown` was incorrectly registered (the `highlightedIndex` is wrong in the callback) so `onSelect` was never called when pressing `Enter` key.
> fix: input attach mode register/unregister callback correctly

- .changeset/large-cars-grow.md
- packages/search-ui/src/Filter/ColorFilter.tsx
- packages/search-ui/src/Filter/test/utils.test.ts
- packages/search-ui/src/Filter/utils.ts
Fixes the bug where incorrect color filter value is included in the search request, this is due to the internal logic of `ColorFilter` as it always convert the filter value response received from backend to be capitalized which leads to this:
> fix: color filter value

- .changeset/spotty-vans-fetch.md
- docs/pages/components/combobox.mdx
- packages/components/src/Combobox/index.tsx
- packages/components/src/Combobox/styles.ts
- packages/components/src/Combobox/types.ts
- packages/components/src/assets/icons/index.tsx
- packages/search-ui/src/Input/types.ts
Add `unstyled` variant and `2xl` size for Combobox to tweak the design of overlay mode:
> feat: add variant prop and 2xl size for Combobox

- .changeset/large-crabs-itch.md
- docs/pages/search-ui/sorting.mdx
- packages/search-ui/src/Sorting/index.tsx
- packages/search-ui/src/Sorting/types.ts
- packages/search-ui/src/ViewOption/styles.ts
Add `list` display option for sorting component. This variant will be used for the mobile version of the overlay mode.
> feat: add list display for sorting component

- .changeset/nine-taxis-poke.md
- docs/pages/classes/filterbuilder.mdx
- docs/pages/classes/rangefilterbuilder.mdx
- docs/pages/hooks/usesearchcontext.mdx
- packages/hooks/src/ContextProvider/controllers/filters/FilterBuilder.ts
- packages/hooks/src/ContextProvider/index.tsx
- packages/hooks/src/ContextProvider/types.ts
Allow `resetFilters` to optionally not emit subscribing events of filters. It is useful when we want to reset all filters to their default value but don't want to trigger a search request.
> feat: support optional emitEvent for resetFilters

- .changeset/hot-hounds-hide.md
- packages/components/src/Combobox/styles.ts
Fix style is broken on Combobox due to `box-sizing` being overridden.
> fix: broken input style

- .changeset/dull-fans-grab.md
- packages/hooks/src/ContextProvider/controllers/filters/RangeFilterBuilder.ts
- packages/hooks/src/useRangeFilter/index.ts
Previously, changing query will remove range filters from the search request via the `reset` function but the update in https://github.com/sajari/sdk-react/commit/66761119165a94ec3a779e0c651ecfb77406dcba was causing the range filters to appear in the request so the return values of aggregate min and max are incorrect.
> fix: incorrect aggregate min max after query change

- .changeset/grumpy-paws-return.md
- packages/components/src/Modal/styles.ts
Without the fix, the pagination is overlapped by the bottom bar of Safari
> fix: modal footer being overlapped by Safari bottom bar

- .changeset/late-bugs-brake.md
- packages/components/src/Combobox/components/Dropdown/index.tsx
Notice the flickering
Call popper's `forceUpdate` as soon as the input receive focus
> Reposition dropdown as soon as input receive focus

- .changeset/calm-files-stare.md
- .changeset/hot-shrimps-talk.md
- docs/pages/hooks/usesorting.mdx
- packages/hooks/src/useSorting/index.ts
- packages/hooks/src/useSorting/types.ts
- yarn.lock
Allow `setSorting` to call without running a search. This is useful when we want to reset the variables but don't want to trigger a search request, for example, to reset the variables after closing the overlay modal so users can start fresh once they re-open the modal.
> feat: allow set sorting without running search

- .changeset/fresh-coins-think.md
- packages/components/src/hooks/useDropdownItemStyles.ts
Fix margin of the menu option is overridden by external CSS. The issue is recorded on https://www.sajari.com/
> fix: margin of menu option is overridden by external CSS

- .changeset/soft-garlics-invite.md
- docs/pages/search-ui/results.mdx
- packages/components/src/Image/styles.ts
- packages/components/src/Image/types.ts
- packages/search-ui/src/Results/components/Result/index.tsx
- packages/search-ui/src/Results/components/Result/styles.ts
- packages/search-ui/src/i18n/locale/en.ts
- packages/utils/src/styles/tailwind.config.js
Add ability to show a product's variant images
It’s worth noting that since this new feature is added it will collide with the current image hover feature. To resolve that, only products that have variant images to show will no longer change on hover.
> feat: variant option

- .changeset/loud-points-double.md
- packages/search-ui/src/Filter/test/utils.test.ts
- packages/search-ui/src/Filter/utils.ts
Fix `capitalize-first-letter` option of textTransform won't work if the text input is all uppercasce.
> fix: capitalize-first-letter not work properly if text input is all uppercase

- .changeset/healthy-frogs-roll.md
- packages/search-ui/src/Filter/test/utils.test.ts
- packages/search-ui/src/Filter/utils.ts
Fix `capitalize` utility works incorrectly, where a string in uppercase letters is not converted to a capitalized output. For example, `hELLO` is converted to `HELLO` instead of `Hello`.
> fix: capitalize util works incorrectly

- .changeset/perfect-jokes-marry.md
- packages/hooks/src/ContextProvider/index.tsx
- packages/hooks/src/useQuery/index.ts
Fix passing a custom `config` object doesn't work.
> fix: custom config not working

- .changeset/dull-penguins-sip.md
- packages/search-ui/src/Filter/ListFilter.tsx
Fix typing in the `Input` will lose focus if it clears the selected items in a list filter. It was because it aims to re-focus on the last selected item once the selected state changed, but since the selected state can be changed by typing on the search input, it will move the focus onto the last selected checkbox.
> fix: input lose focus if clear a list filter

- .changeset/tricky-seahorses-hammer.md
- docs/pages/classes/config.mdx
- docs/pages/classes/variables.mdx
- packages/hooks/src/ContextProvider/Config.ts
- packages/hooks/src/ContextProvider/controllers/Variables.ts
Include `fields:''` in the body request to always expect `_id` to be in the response. It's necessary, otherwise, it could break the re-render process of Results where the `key` relies on the `_id`.
> fix: missing _id in the response

- yarn.lock
> chore: update caniuse target list to squelch warnings.

- .changeset/ten-files-move.md
- package.json
- tsconfig.json
- yarn.lock
Before change, tsc results in 626 errors.
After change, 18 errors.
It's possible to get this down to ~6 but that requires bumping and reconfiguring emotion. I've already spent more time on this than I wanted so I'm moving forward without doing that.
> chore: cleanup typescript errors

- .changeset/afraid-rabbits-compare.md
- packages/components/src/Modal/styles.ts
- packages/utils/src/styles/tailwind.config.js
Fix the issue when the footer of the modal gets hidden on iPad. It was because we used `vh` to limit the max height of the modal content, but on mobile browsers, the bottom bar is not part the the `100vh` height so the bottom UI will be cut off when the address bar is visible. For more details, see https://chanind.github.io/javascript/2019/09/28/avoid-100vh-on-mobile-web.html.
> fix: modal footer gets hidden on ipad

- .changeset/cyan-foxes-check.md
- packages/hooks/package.json
- packages/hooks/src/ContextProvider/controllers/Pipeline.test.ts
- packages/hooks/src/ContextProvider/controllers/Pipeline.ts
- packages/hooks/src/ContextProvider/controllers/fixtures/Pipeline.ts
- yarn.lock
Gives the ability pass a custom click token url for use in staging environments. Allows end to end testing of clicktracking.
> feat: support custom clicktracking url so we can test in non-prod environments

- .changeset/gentle-carrots-tickle.md
Fix missing bump utils package for components and search-ui packages in https://github.com/sajari/sdk-react/pull/598.
> feat: change Tailwind unit from rem to em

- .changeset/fuzzy-dots-press.md
- packages/components/src/RangeInput/index.tsx
Fix range input handles overlap if `min` is to `max`.
**Before**
**After**
> fix: range input handles overlap

- .changeset/hungry-keys-whisper.md
- packages/utils/src/styles/cache.ts
Fix missing setting key for emotion cache which causes a warning if an app requires using multiple emotion caches - https://emotion.sh/docs/@emotion/cache#key. 
Resolve #605
> fix: missing emotion cache key

- .changeset/sharp-seahorses-grab.md
- packages/search-ui/src/Input/types.ts
Fix `Input` doesn't accept HTML attributes like `name`. 
Also, fallback type param to `unknown` so we don't have to pass `any` when using the `InputProps` interface.
> fix: input does not accept HTML attributes

- .changeset/proud-bulldogs-try.md
- packages/search-ui/src/Input/index.tsx
- packages/search-ui/src/Results/components/Result/index.tsx
- packages/search-ui/src/Results/components/Result/types.ts
- packages/search-ui/src/hooks/index.ts
- packages/search-ui/src/utils/applyClickTracking.test.ts
- packages/search-ui/src/utils/applyClickTracking.ts
- packages/search-ui/src/utils/applyPosNegTracking.ts
- packages/search-ui/src/utils/index.ts
This PR renames the `useClickTracking` and `usePosNegTracking` hook to use the `apply` prefix instead, so:
- `useClickTracking` -> `applyClickTracking`
- `usePosNegTracking` -> `applyPosNegTracking`
We can consider keeping both the old and new API and have a plan for deprecation later on @wwalser
> fix: rename misleading hooks

- .changeset/nice-bags-sip.md
- packages/utils/src/assertion.ts
chore: ie11 support by working around lack of toString.call
> chore: ie11 support by working around lack of toString.call

- .changeset/cyan-weeks-visit.md
- packages/components/package.json
- packages/search-ui/package.json
- packages/server/package.json
chore: bump packages and require latest version of sdk-utils
> chore: bump packages and require latest version of sdk-utils

- packages/hooks/src/ContextProvider/controllers/Pipeline.ts
- packages/hooks/src/ContextProvider/controllers/analytics/Analytics.ts
- packages/hooks/src/ContextProvider/controllers/analytics/DebugAnalytics.ts
- packages/hooks/src/ContextProvider/controllers/analytics/GoogleAnalytics.ts
- packages/hooks/src/ContextProvider/controllers/analytics/index.ts
- packages/hooks/src/ContextProvider/controllers/index.ts
- packages/search-ui/src/Results/components/Result/index.tsx
- packages/search-ui/src/Results/components/TemplateResult/types.ts
- packages/search-ui/src/Results/types.ts
Using the `import type` feature of TypeScript
ref: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export
> fix: remove import/cycle eslint ignore

- .changeset/rotten-candles-attack.md
- docs/pages/search-ui/results.mdx
- packages/search-ui/src/Results/components/Result/index.tsx
- packages/search-ui/src/Results/components/Result/types.ts
- packages/search-ui/src/Results/components/TemplateResult/index.tsx
- packages/search-ui/src/Results/components/TemplateResult/types.ts
- packages/search-ui/src/Results/components/TemplateResults/index.tsx
- packages/search-ui/src/Results/components/TemplateResults/types.ts
- packages/search-ui/src/Results/index.tsx
- packages/search-ui/src/Results/useHoverImage.ts
- packages/search-ui/src/Results/useProductImages.ts
- packages/search-ui/src/Results/useProductStatuses.ts
- packages/search-ui/src/Results/useRenderPrice.ts
- packages/utils/src/react-helpers.ts
When changing to use result template, we need to keep the following existing features that is offered out-of-the-box when using the `Result` component:
> feat: add support for features of Result component to result template

- .changeset/afraid-items-obey.md
- packages/search-ui/src/Results/useProductImages.ts
Need to clear the images container when toggling the variant image option or the old images will stack up.
> fix: clear container when toggling show variant image option

- .changeset/silly-cups-matter.md
- packages/components/src/Combobox/components/Typeahead/index.tsx
- packages/components/src/Combobox/components/Typeahead/styles.ts
- packages/components/src/Combobox/context.tsx
- packages/components/src/Combobox/index.tsx
- packages/components/src/Combobox/styles.ts
- packages/components/src/Combobox/types.ts
Fix typeahead text overlaps the input text.
Note that there is a "line-height" issue if the input size is greater than `xl` due to the absolute position of the input. Fixing the issue was time-consuming for me so I would suggest we move forward with the PR since the 2xl input is not commonly used and I will propose another PR to fix it later.
> fix: input typeahead mode is broken

- .changeset/small-fishes-crash.md
- packages/search-ui/src/Results/useProductStatuses.ts
- packages/search-ui/src/Results/useRenderPrice.ts
This PR will add another variable called `isCurrentOnSale` this is different from `isOnSale` from that `isOnSale` will be true if at least one of the variant products is on sale. On the other hand, `isCurrentOnSale` is only of that variant product.
> fix: render price logic when showing variant images

- .changeset/nasty-eels-relate.md
- packages/search-ui/src/Results/components/Message/index.tsx
- packages/search-ui/src/Results/components/Message/styles.ts
Recover margin-top for the reset button in `Message` component.
Also, make the button bigger. See:
> fix: reset button missing margin top

- package.json
- yarn.lock
chore: upgrade tslib to quiet array spread warnings
> chore: upgrade tslib to quiet array spread warnings

- .changeset/popular-pumas-boil.md
- packages/hooks/src/ContextProvider/controllers/filters/RangeFilterBuilder.ts
- packages/hooks/src/ContextProvider/controllers/filters/test/RangeFilterBuilder.test.ts
- packages/hooks/src/ContextProvider/controllers/filters/test/combineFilters.test.ts
fix: avoid sending range filter when min and max values are set to the min and max of the collection
> Don't send unchanged range filter values

- .github/workflows/release.yml
github: rename release pr to better indicate what it does.
> github: rename release pr to better indicate what it does.

- .changeset/popular-clouds-learn.md
- packages/search-ui/src/Input/index.tsx
Remove `resetFilters` when calling autocomplete search. This trigger of the method is not only unnecessary, but it also introduces a mess in SearchContext to override the input value.
https://search-io.atlassian.net/browse/SF-705
> fix: remove unwanted resetFilters from autocomplete search

- .changeset/hot-files-hang.md
- packages/search-ui/src/Results/components/BannerItem/index.tsx
- packages/search-ui/src/Results/components/BannerItem/styles.ts
This should fix the issue where the banner height is larger than the row's items height and therefore expanding the row height (see below)
After the fix it should look like this
However, when the banner's height is smaller than the item's height then the following happens (the banner doesn't span all the full height), maybe @zlatanpham or @chidojiro would have an idea.
> fix: banner should not expand row height

- .changeset/late-actors-destroy.md
- docs/pages/search-ui/results.mdx
- packages/search-ui/src/Results/components/BannerItem/index.tsx
- packages/search-ui/src/Results/components/BannerItem/types.ts
- packages/search-ui/src/Results/components/TemplateResults/index.tsx
- packages/search-ui/src/Results/components/TemplateResults/types.ts
- packages/search-ui/src/Results/index.tsx
This PR wrap the custom result template container with ResizeObserver (similar to the normal `Result` component). The reason is to get rid of extra responsive CSS that we have to inject along with the code snippet and to provide responsive support for banners.
> fix: add resize observer for custom template

- .changeset/many-jokes-design.md
- packages/components/package.json
- packages/hooks/package.json
- packages/search-ui/package.json
- packages/server/package.json
- packages/utils/package.json
Fixes this sort of thing:
```
$ npm i @sajari/react-search-ui --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: tw-test@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from @sajari/react-search-ui@4.13.1
npm ERR! node_modules/@sajari/react-search-ui
npm ERR!   @sajari/react-search-ui@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/jberry/.npm/eresolve-report.txt for a full …
```
> chore(deps): correct react peer deps to be >=16.8.0

- .changeset/little-dolphins-worry.md
- packages/search-ui/src/ContextProvider/index.tsx
- packages/search-ui/src/ContextProvider/types.ts
- packages/search-ui/src/Results/components/Result/index.test.tsx
- packages/search-ui/src/Results/components/Result/index.tsx
- packages/search-ui/src/Results/components/Result/types.ts
- packages/search-ui/src/Results/index.tsx
resolve: https://search-io.atlassian.net/jira/software/projects/SF/boards/29?selectedIssue=SF-641
diagnose: rerenders happen so many times that makes the even loop busy and slow to process input events
solution: make items of Results independent from any context
> fix: performance issue on results

- .changeset/thick-bags-bake.md
- packages/search-ui/src/Input/index.test.tsx
- packages/search-ui/src/Input/index.tsx
This PR removes the blur behavior after the user presses enter because it doesn't allow them to search again immediately. Instead, a `readonly` attribute is added to preserve the focus while still preventing the user from repeatedly spamming enter key, after a search is done the attribute is removed.
Credit goes to @JasonBerry for the solution idea.
> fix: enter behavior in input

- .changeset/brown-rings-greet.md
- packages/search-ui/src/Results/components/Result/index.tsx
- packages/search-ui/src/Results/useRenderPrice.test.ts
- packages/search-ui/src/Results/useRenderPrice.ts
Currently, the `useRenderPrice` hook return the value `null` in some cases, this is not a problem with our standard `Result` component because we already perform checks before rendering. However, this will potentially break in result template mode because users wouldn't expect `productPrice` to be null (maybe it's not too obvious/not documented somewhere)
Instead of returning null in those cases, we return the same object shape but with an empty string, this will have the same effect as if the user would have to write a check before rendering in the template code themselves
> fix: product price null as return value

- .changeset/friendly-walls-taste.md
- packages/search-ui/src/Results/utils.test.ts
- packages/search-ui/src/Results/utils.ts
Fix the output of `mergeBannersWithResults` will contain `undefined` value if there is a banner having a position greater than the total number of the combination between banners and results. The `undefined` value will cause the check of `isBanner` method to break and crash the app.
> fix: update mergeBannersWithResults to handle edge case

- .changeset/cyan-buttons-allow.md
- packages/components/src/Box/test/Box.test.tsx
- packages/components/src/Button/index.tsx
- packages/components/src/Button/test/Button.test.tsx
- packages/components/src/ButtonGroup/test/ButtonGroup.test.tsx
- packages/components/src/Checkbox/test/Checkbox.test.tsx
- packages/components/src/Combobox/test/Combobox.test.tsx
- packages/components/src/Heading/test/Heading.test.tsx
- packages/components/src/Image/test/Image.test.tsx
- packages/components/src/Label/test/Label.test.tsx
- packages/components/src/Link/test/Link.test.tsx
- packages/components/src/Pagination/test/Pagination.test.tsx
- packages/components/src/Radio/test/Radio.test.tsx
- packages/components/src/RangeInput/test/RangeInput.test.tsx
- packages/components/src/Select/index.tsx
- packages/components/src/Select/test/Select.test.tsx
- packages/components/src/Tabs/test/Tabs.test.tsx
- packages/components/src/Text/test/Text.test.tsx
Ensure components from the SDK support additional `data-*` attributes, for example, passing `data-testid` is helpful for writing tests for the components.
> fix: support ability to add data-* attrs

- .changeset/two-actors-exist.md
- packages/hooks/src/ContextProvider/controllers/tracking/EventTracking.test.ts
- packages/hooks/src/ContextProvider/controllers/tracking/EventTracking.ts
This should enable easier ad-hoc event tracking support, like:
```typescript
import { EventTracking, SearchIOAnalytics } from '@sajari/react-hooks';
const account = '1594153711901724220';
const collection = 'bestbuy';
const searchIOAnalytics = new SearchIOAnalytics(account, collection);
const eventTracking = new EventTracking('id', undefined, searchIOAnalytics);
const pipeline = new Pipeline({ account, collection, }, 'query', eventTracking);
// e.g. in add to cart buttons - doesn't require React context, etc
searchIOAnalytics.track('add_to_cart', product.id);
```
In this way the React components share the same `SearchIOAnalytics` instance as wherever else we might need to track events, so the latest `queryId` will be updated by the pipeline query and correctly bound to the events tracked …
> feat: add ability to pass custom SearchIOAnalytics instance to EventTracking

- .changeset/heavy-beers-end.md
- packages/components/src/Combobox/styles.ts
The actual text vs the typeahead text is not perfectly vertically aligned
It seems the `height` property is making the input behave differently somehow so I've removed that and added a `min-height: 100%` as a fallback instead. See vid
https://user-images.githubusercontent.com/25856620/163996061-f8d295b9-9cca-4d16-9841-32ee93f60fab.mov
https://user-images.githubusercontent.com/25856620/163996124-e7dd028e-f1d7-403c-b140-9383a27e6a47.mov
SF-549
> fix: different height of typeahead

- .changeset/fast-ducks-tan.md
- packages/search-ui/src/Input/index.test.tsx
One of the Input test that tests for the `readonly` attribute being set properly when the user spams the Enter key is unstable, it fails occasionally.
Remove the statement where it is failing, I think it's reasonable given that we don't actually want to test for the inside mechanism of how it works but rather than just the expected result that we will get.
> fix: unstable input test

- .changeset/poor-penguins-fry.md
- packages/search-ui/src/Filter/ColorFilter.tsx
- packages/search-ui/src/Filter/ListFilter.tsx
- packages/search-ui/src/Filter/SelectFilter.tsx
- packages/search-ui/src/Filter/TabFilter.tsx
[SF-575](https://search-io.atlassian.net/jira/software/projects/SF/boards/29?selectedIssue=SF-575)
___
Noting that showing filters that only have one option seems to have been a conscious decision in the past. Refer to [this commit]( https://github.com/sajari/sdk-react/commit/1e6194089ccd86f5ddc9c872c9710ca789960617).
> fix: hide filters with only one option

- .changeset/eighty-planes-applaud.md
- packages/search-ui/src/Filter/Box.tsx
- packages/search-ui/src/Filter/ColorFilter.tsx
- packages/search-ui/src/Filter/ListFilter.tsx
- packages/search-ui/src/Filter/RangeFilter.tsx
- packages/search-ui/src/Filter/RatingFilter.tsx
- packages/search-ui/src/Filter/SelectFilter.tsx
- packages/search-ui/src/Filter/TabFilter.tsx
- packages/search-ui/src/Filter/types.ts
Add support custom attributes for `Fitler` component. After the change, we can add attributes such as `data-testid` to easily query the component in e2e tests. Usage:
```
<Filter data-testid="rating-filter" type="select" name="category" title="Category" searchable sort="alpha" />
```
> fix: support custom attrs for Filter component

- packages/hooks/src/ContextProvider/context.ts
- packages/hooks/src/ContextProvider/index.tsx
- packages/hooks/src/ContextProvider/types.ts
- packages/hooks/src/URLStateSync/index.tsx
- packages/hooks/src/URLStateSync/types.ts
- packages/hooks/src/useFilter/index.ts
- packages/hooks/src/usePagination/index.ts
- packages/hooks/src/useQuery/index.ts
- packages/hooks/src/useRangeFilter/index.ts
- packages/hooks/src/useResultsPerPage/index.ts
- packages/hooks/src/useSearchContext/index.ts
- packages/hooks/src/useSorting/index.ts
- packages/hooks/src/utils/queryParams.ts
- packages/hooks/src/utils/response.ts
- packages/search-ui/src/ContextProvider/index.tsx
In the existing implementation, the initial data is set at the hook level so that methods like `filter.set` will emit search events to cause multiple API calls after the app is loaded. Instead, the data should be initialized before filters and variables are passed to `SearchProvider`.
**Note: need to fix cycle import issue.**
> fix: multiple API calls due to init data at hook level (WIP)

- .github/workflows/release.yml
Resolve [the warning](https://github.com/sajari/sdk-react/runs/6569193910?check_suite_focus=true) for changeset CI: 
> Warning: The workflow file using `changesets/action` is currently using `@master` as the version. This branch has been frozen and deprecated. Please update your workflow to either use `@v1` or a specific commit SHA that is tagged.
> ci: target changeset@v1 to avoid warning

- .changeset/fifty-paws-dream.md
- packages/hooks/src/utils/queryParams.test.ts
- packages/hooks/src/utils/queryParams.ts
Fix initial value for a filter will be overridden to an empty value if the URL param doesn't exist.
> fix: initial filter overridden even if URL param is empty

- .changeset/fifty-cycles-walk.md
- packages/search-ui/src/Results/components/TemplateResults/index.tsx
- packages/search-ui/src/Results/resultTemplateHelpers.test.ts
- packages/search-ui/src/Results/resultTemplateHelpers.ts
- Add a `join` helper in result template to conveniently render list of items such as categories e.g "Furniture > Chair > Brown Chair"
```hbs
{{#join items=["Furniture", "Chair", "Brown Chair"] joiner=" > "}}
```
> feat: add "join" helper to result template

- .changeset/eleven-insects-hear.md
- packages/components/src/PoweredBy/index.tsx
Change `PoweredBy` component text from 'Powered by Search.io' to 'Site search by Search.io`.
[SF-866](https://search-io.atlassian.net/browse/SF-866)
_____
> feat: update PoweredBy text

- .changeset/silver-scissors-mate.md
- packages/hooks/src/ContextProvider/index.tsx
- packages/hooks/src/ContextProvider/types.ts
- packages/hooks/src/URLStateSync/index.tsx
- packages/hooks/src/useResultsPerPage/index.ts
- packages/hooks/src/useResultsPerPage/types.ts
Fix the issue when changing the default value of `resultsPerPage` to a value that is different from `15` will cause URL param injection.
> fix: url param injection due to changing default resultsPerPage value

- .changeset/short-humans-kiss.md
- packages/hooks/src/ContextProvider/index.tsx
- packages/hooks/src/ContextProvider/types.ts
- packages/hooks/src/URLStateSync/config.ts
- packages/hooks/src/URLStateSync/index.tsx
- packages/hooks/src/URLStateSync/types.ts
Allow changing the URL param keys which previously are hard-coded. For example, `?q=xxx` can be changed to `?query=xxx`. Default mapping keys:
```js
{
q: 'q',
resultsPerPage: 'show',
page: 'page',
sort: 'sort',
}
```
> fix: allow to config URL param keys

- .changeset/short-jeans-rule.md
- packages/search-ui/src/Results/components/BannerItem/index.tsx
There's a fair amount of styling simplification and removal of extraneous elements that could be applied but I didn't want to dive into that without storybooks or something that would allow me to play with all the different permutations of displaying results.
> fix: make promo overlays clickable

- .changeset/plenty-goats-tan.md
- .changeset/strong-tomatoes-sneeze.md
- .eslintrc
- docs/pages/search-ui/input.mdx
- packages/search-ui/src/Input/index.test.tsx
- packages/search-ui/src/Input/index.tsx
- packages/search-ui/src/Input/utils/index.test.ts
- packages/search-ui/src/Input/utils/index.ts
Assume users don't care about the case-sensitivity of redirects and lowercase all inputs when retrieving redirects, as well as the redirect keys themselves (the queries that trigger the redirects).
[DAU-249](https://algolia.atlassian.net/browse/DAU-249)
> feat: make redirects via the input component case-insensitive
