src/controllers/aggregateFilter.ts, src/controllers/index.ts, src/index.ts
=> Aggregate filter controller

src/components/Input/Input.tsx, src/components/Input/Results.tsx, src/components/Input/Suggestions.tsx, src/components/Input/shared/Dropdown.tsx, src/components/Input/shared/utils.test.ts, src/components/Input/shared/utils.ts, src/components/Search/Search.tsx, src/components/Search/index.ts, src/components/Search/search.mdx, src/components/Search/utils.test.ts, src/components/Search/utils.ts, src/components/index.ts, src/docs/icons.tsx, src/index.ts
=> Search render prop

src/components/Checkbox/Checkbox.tsx, src/components/Checkbox/checkbox.mdx
Add an `all` props to `<Checkbox />` component to allow for check-all option.
=> Add 'All' option for checkbox

package.json, src/components/RangeSlider/RangeSlider.tsx, src/components/RangeSlider/RangeSliderUI.tsx, src/components/RangeSlider/index.ts, src/components/RangeSlider/rangeSlider.mdx, src/components/RangeSlider/styled.tsx, src/components/index.ts, src/controllers/index.ts, src/controllers/rangeAggregrateFilter.ts, src/controllers/rangeFilter.ts, src/index.ts, yarn.lock
This PR aims to create RangeSlider which will be used to narrow down search results, for example, based on pricing.
=> rangeSlider component

src/components/Checkbox/Checkbox.tsx
=> Add readonly prop to the checkbox input

src/components/Box/Box.mdx, src/components/Box/Box.tsx, src/components/Box/index.tsx, src/types/component-as.ts, src/utils/forwardRefWithAs.ts
-  [x] Add utilities for handling with `as` prop for polymorphic component
-  [x] Add `Box` component
=> Add Box component

src/components/Box/Box.mdx, src/components/Box/Box.tsx, src/components/Box/index.tsx, src/types/component-as.ts, src/utils/forwardRefWithAs.ts
This PR is created to merge the changes to `v3` branch
=> Add Box component (to v3)

src/components/Radio/Radio.mdx, src/components/Radio/index.tsx, src/components/Radio/types.ts, src/components/RadioGroup/index.tsx, src/components/RadioGroup/types.ts
This change depends on https://github.com/sajari/sajari-sdk-react/pull/154
=> V3: Add RadioGroup component

src/components/Image/Image.mdx, src/components/Image/index.tsx, src/components/Image/types.ts
A clone from the component library.
=> V3: Add Image component

src/components/Image/index.tsx
Quick one, probably slipped through when rebasing.
=> V3: Fix Image typo

packages/components/src/ButtonGroup/index.tsx
Fix the styling bug of the ellipsis
=> V3: Edit styling of button group

packages/components/src/ButtonGroup/index.tsx
Hey @sampotts, the styling PR didn't build successfully and I was going to push a new change but you were so fast :), sorry I shouldn't request the review so soon.
=> V3: Add typing for button group

docs/pages/swatch.mdx, packages/components/src/Swatch/color.tsx, packages/components/src/Swatch/context.tsx, packages/components/src/Swatch/index.tsx
=> V3: chore/fine-tune swatch component

packages/components/src/Box/index.tsx, packages/components/src/Box/props-blacklist.ts, packages/components/src/Pagination/index.tsx, packages/styles/src/index.ts, packages/styles/src/utils/index.ts, packages/styles/src/utils/object.ts, packages/styles/src/utils/test/object.test.ts
=> V3: fix/minor fixes

packages/components/src/Combobox/index.tsx
Move the props inside Downshift's `props getter` to prevent them being overridden
=> fix: combobox downshift props getter

docs/pages/hooks/usepagination.mdx, example/index.tsx, packages/hooks/src/index.ts, packages/hooks/src/usePagination/index.ts, packages/hooks/src/usePagination/types.ts, packages/hooks/src/useSearchContext/index.ts, yarn.lock
=> V3: feat/add usePagination hook

packages/hooks/src/SearchContextProvider/index.tsx, packages/hooks/src/index.ts
=> V3: fix: duplicate export

docs/components/components.ts, docs/pages/search-ui/summary.mdx, packages/search-ui/src/Summary/index.tsx, packages/search-ui/src/index.ts
This change depends on https://github.com/sajari/sajari-sdk-react/pull/180.
=> V3: add summary composition

docs/pages/search-ui/result.mdx, docs/pages/search-ui/results.mdx, packages/search-ui/src/Result/index.tsx, packages/search-ui/src/Results/index.tsx, packages/search-ui/src/Results/styles.ts, packages/search-ui/src/Results/types.ts, packages/search-ui/src/index.ts
This change depends on https://github.com/sajari/sajari-sdk-react/pull/180
=> V3: add results composition

packages/components/src/RangeInput/index.tsx, packages/components/src/index.ts, packages/hooks/src/SearchContextProvider/controllers/index.ts, packages/hooks/src/SearchContextProvider/index.tsx
I will add the build step to Travis CI to ensure the error will be caught in the scope of a PR so we don't have to open a fix like this in the future.
=> V3: fix eslint warning causing build fail

docs/pages/hooks/usepagesize.mdx, docs/pages/hooks/usepagination.mdx, docs/pages/hooks/usesorting.mdx, docs/pages/search-ui/pagesize.mdx, docs/pages/search-ui/result.mdx, docs/pages/search-ui/sorting.mdx, packages/hooks/src/SearchContextProvider/types.ts, packages/search-ui/src/PageSize/index.tsx, packages/search-ui/src/Result/index.tsx, packages/search-ui/src/Result/styles.ts, packages/search-ui/src/Results/index.tsx, packages/search-ui/src/Results/styles.ts, packages/search-ui/src/Sorting/index.tsx
=> V3: chore: polish

docs/pages/hooks/usepagesize.mdx, docs/pages/hooks/usepagination.mdx, docs/pages/hooks/usesorting.mdx, docs/pages/search-ui/pagesize.mdx, docs/pages/search-ui/sorting.mdx, packages/hooks/src/SearchContextProvider/controllers/pipeline.ts, packages/hooks/src/SearchContextProvider/index.tsx, packages/hooks/src/index.ts
=> V3: fix: broken analytics in pipeline

docs/components/CodeBlock.tsx, docs/pages/_app.tsx, docs/pages/search-ui/filter.mdx, packages/components/src/Button/styles.ts, packages/components/src/Heading/types.ts, packages/components/src/Swatch/colors.ts, packages/components/src/Swatch/index.tsx, packages/hooks/src/index.ts, packages/hooks/src/useFilter/index.ts, packages/search-ui/src/Filter/Box.tsx, packages/search-ui/src/Filter/ColorFilter.tsx, packages/search-ui/src/Filter/Header.tsx, packages/search-ui/src/Filter/ListFilter.tsx, packages/search-ui/src/Filter/index.tsx, packages/search-ui/src/Filter/test/utils.test.ts, packages/search-ui/src/Filter/types.ts, packages/search-ui/src/Filter/utils.ts, packages/search-ui/src/assets/icons/index.tsx, packages/search-ui/src/assets/icons/small-chevron-down.svg, packages/search-ui/src/assets/icons/small-chevron-up.svg, packages/search-ui/src/index.ts
Added `Filter` component for `search-ui` package. Currently,  it supports `list` and `color` type.
=> V3: add Filter composition

docs/components/Navigation/SideNav.tsx, docs/components/components.ts, docs/pages/hooks/usetracking.mdx, docs/pages/tracking/clicktracking.mdx, docs/pages/tracking/index.mdx, docs/pages/tracking/notracking.mdx, docs/pages/tracking/posnegtracking.mdx, packages/hooks/src/SearchContextProvider/controllers/pipeline.ts, packages/hooks/src/index.ts, packages/hooks/src/useTracking/index.ts, packages/hooks/src/useTracking/types.ts, packages/search-ui/src/Results/Result/index.tsx, packages/search-ui/src/Results/Result/types.ts, packages/search-ui/src/Results/index.tsx
=> V3: chore: re-enable tracking

docs/pages/tracking/clicktracking.mdx, docs/pages/tracking/notracking.mdx, docs/pages/tracking/posnegtracking.mdx
Some docs still reference the `Values`.
=> V3: fix: leftover Values reference

docs/pages/search-ui/viewtype.mdx, packages/hooks/src/SearchContextProvider/index.tsx, packages/hooks/src/utils/assertion.ts, packages/search-ui/src/ViewType/index.tsx, packages/search-ui/src/ViewType/types.ts
=> V3: chore: add missing logic in viewtype

docs/components/components.ts, docs/pages/hooks/usevariables.mdx, packages/hooks/src/index.ts, packages/hooks/src/useVariables/index.ts, packages/hooks/src/useVariables/types.ts
=> V3: chore: create useVariables hook

docs/pages/hooks/usefilter.mdx, docs/pages/search-ui/filter.mdx, docs/pages/tracking/clicktracking.mdx, docs/pages/tracking/notracking.mdx, docs/pages/tracking/posnegtracking.mdx
=> chore: improve document

packages/hooks/src/useSearch/index.ts
=> fix: search function in useSearch

packages/hooks/src/SearchContextProvider/index.tsx, packages/hooks/src/useFilter/index.ts, packages/search-ui/src/Results/Result/index.tsx
=> fix: performance

packages/hooks/src/useSearch/index.ts, packages/hooks/src/useSearch/types.ts
=> V3: chore: expose searchInstant method and suggestions result

docs/pages/components/combobox.mdx, packages/components/src/Combobox/components/Dropdown/index.tsx, packages/components/src/Combobox/components/DropdownItem/index.tsx, packages/components/src/Combobox/components/DropdownResult/index.tsx, packages/components/src/Combobox/components/DropdownResult/styles.ts, packages/components/src/Combobox/components/DropdownResult/types.ts, packages/components/src/Combobox/context.tsx, packages/components/src/Combobox/index.tsx, packages/components/src/Combobox/types.ts
This PR aims to retain the functionality we had in v2
=> V3: improve combobox UX

.travis.yml, packages/components/src/AspectRatio/index.tsx, packages/components/src/Image/index.tsx, packages/hooks/src/SearchContextProvider/controllers/filters/test/Filter.test.ts, packages/hooks/src/SearchContextProvider/controllers/filters/test/combineFilters.test.ts, packages/hooks/src/useSearch/index.ts, packages/hooks/src/useSearch/types.ts, packages/hooks/src/utils/test/mapResultFields.test.ts, packages/search-ui/src/Filter/test/utils.test.ts, packages/search-ui/src/Filter/utils.ts
=> V3: minor fixes

packages/hooks/src/useSearchContext/index.ts, packages/search-ui/src/Summary/index.tsx
=> V3: improve Summary UX

docs/pages/components/aspectratio.mdx
=> V3: change the image example of AspectRatio

docs/components/SearchProvider.tsx, docs/pages/hooks/usefilter.mdx, docs/pages/hooks/usepagesize.mdx, docs/pages/hooks/usepagination.mdx, docs/pages/hooks/usesorting.mdx, docs/pages/search-ui/filter.mdx, docs/pages/search-ui/pagesize.mdx, docs/pages/search-ui/pagination.mdx, docs/pages/search-ui/sorting.mdx, docs/pages/search-ui/viewtype.mdx, docs/pages/tracking/clicktracking.mdx, docs/pages/tracking/notracking.mdx, docs/pages/tracking/posnegtracking.mdx, example/index.tsx, packages/hooks/src/SearchContextProvider/controllers/variables.ts
=> V3: simplify variable

packages/hooks/src/SearchContextProvider/controllers/variables.ts, packages/hooks/src/usePageSize/index.ts, packages/hooks/src/usePagination/index.ts, packages/search-ui/src/PageSize/index.tsx
=> V3: increase page size option

docs/pages/hooks/usesearch.mdx, packages/hooks/src/useSearch/index.ts, packages/hooks/src/useSearch/types.ts
=> V3: fix useSearch

docs/pages/search-ui/results.mdx, docs/pages/search-ui/viewtype.mdx, packages/search-ui/src/Results/index.tsx, packages/search-ui/src/Results/types.ts
=> V3: fix results appearance

docs/pages/search-ui/filter.mdx, packages/search-ui/src/ContextProvider/index.tsx, packages/search-ui/src/ContextProvider/types.ts, packages/search-ui/src/Filter/RatingFilter.tsx, packages/search-ui/src/Filter/index.tsx, packages/search-ui/src/Filter/types.ts, packages/search-ui/src/Results/index.tsx
=> feat: add rating filter

docs/components/CodeBlock.tsx, docs/pages/search-ui/filter.mdx, packages/components/src/Tabs/TabList/index.tsx, packages/components/src/Tabs/TabList/styles.ts, packages/search-ui/src/Filter/ColorFilter.tsx, packages/search-ui/src/Filter/ListFilter.tsx, packages/search-ui/src/Filter/TabFilter.tsx, packages/search-ui/src/Filter/index.tsx, packages/search-ui/src/Filter/types.ts, packages/search-ui/src/i18n/locale/en.json
Adds support for `<Filter type="tabs">`.
=> feat: added TabFilter component

packages/search-ui/src/ContextProvider/types.ts, packages/search-ui/src/ViewType/index.tsx, packages/search-ui/src/ViewType/styles.ts, packages/search-ui/src/ViewType/types.ts
Add options to control styles for ViewType component:
=> feat: add option to control styles for ViewType

packages/components/src/Combobox/index.tsx, packages/hooks/src/SearchContextProvider/index.tsx, packages/hooks/src/useFilter/index.ts, packages/hooks/src/useSearch/index.ts, packages/search-ui/src/Input/index.tsx
=> V3: improve performance

packages/search-ui/src/ContextProvider/types.ts, packages/search-ui/src/Sorting/index.tsx, packages/search-ui/src/Sorting/styles.ts, packages/search-ui/src/Sorting/types.ts
Add options to control styles for Sorting component:
=> V3: add option to control styles for Sorting

packages/hooks/src/SearchContextProvider/index.tsx, packages/hooks/src/SearchContextProvider/types.ts
=> V3: fix correct type for variables

docs/components/CodeBlock.tsx, docs/components/Navigation/SideNav.tsx, docs/components/components.ts, docs/pages/examples/basic.mdx, packages/hooks/src/SearchContextProvider/index.tsx
=> V3: reset to page 1 when apply filter

packages/search-ui/src/ContextProvider/types.ts, packages/search-ui/src/Results/components/Message/index.tsx, packages/search-ui/src/Results/components/Message/styles.ts, packages/search-ui/src/Results/components/Message/types.ts, packages/search-ui/src/Results/components/Result/index.tsx, packages/search-ui/src/Results/components/Result/styles.ts, packages/search-ui/src/Results/components/Result/types.ts, packages/search-ui/src/Results/index.tsx, packages/search-ui/src/Results/styles.ts, packages/search-ui/src/Results/types.ts
Add options to control styles for Results component:
=> V3: add option to control styles for Results

packages/components/src/Combobox/components/Dropdown/index.tsx, packages/components/src/Combobox/components/Dropdown/styles.ts, packages/components/src/Combobox/components/DropdownItem/index.tsx, packages/components/src/Combobox/components/DropdownItem/styles.ts, packages/components/src/Combobox/components/DropdownResult/index.tsx, packages/components/src/Combobox/components/Typeahead/index.tsx, packages/components/src/Combobox/components/Voice/index.tsx, packages/components/src/Combobox/components/Voice/styles.ts, packages/components/src/Combobox/context.tsx, packages/components/src/Combobox/index.tsx, packages/components/src/Combobox/styles.ts, packages/components/src/Combobox/types.ts, packages/search-ui/src/ContextProvider/types.ts, packages/search-ui/src/Input/index.tsx, packages/search-ui/src/Input/types.ts
Add options to control styles for Input and Combobox component:
=> V3: add option to control styles for Combobox and Input

docs/pages/search-ui/pagination.mdx, docs/pages/search-ui/results.mdx, docs/pages/search-ui/summary.mdx, packages/hooks/src/useSearch/index.ts
=> V3: fix empty query search logic

docs/pages/search-ui/summary.mdx, packages/search-ui/src/Summary/index.tsx, packages/search-ui/src/Summary/types.ts
=> V3: fix summary disable suggestion by default

packages/components/src/Rating/RatingItem.tsx, packages/components/src/Rating/index.tsx, packages/components/src/Rating/styles.ts
Add option to disable styles for Rating component.
=> V3: add option to control styles for Rating

packages/hooks/src/ContextProvider/controllers/analytics/analytics.ts, packages/hooks/src/ContextProvider/controllers/analytics/ga.ts, packages/search-ui/src/Filter/utils.ts, packages/utils/src/index.ts, packages/utils/src/number.ts, packages/utils/src/ssr.ts
=> V3: add ssr helper to utils

docs/pages/components/pagination.mdx, docs/pages/search-ui/pagination.mdx, packages/components/package.json, packages/components/src/Pagination/index.tsx, packages/components/src/Pagination/types.ts, packages/components/src/hooks/index.ts, packages/components/src/hooks/useFirstRender.ts, packages/components/src/index.ts, packages/search-ui/src/Pagination/index.tsx, packages/search-ui/src/Pagination/types.ts, yarn.lock
I couldn't work out the solution to the first child of context problem, but even if there is one I don't think it'll be trivial.
=> V3: add scrolling option

packages/components/src/RangeInput/components/Fill/index.tsx, packages/components/src/RangeInput/components/Fill/styles.ts, packages/components/src/RangeInput/components/Fill/types.ts, packages/components/src/RangeInput/components/Handle/index.tsx, packages/components/src/RangeInput/components/Handle/styles.ts, packages/components/src/RangeInput/components/Handle/types.ts, packages/components/src/RangeInput/components/Input/index.tsx, packages/components/src/RangeInput/components/Input/styles.ts, packages/components/src/RangeInput/components/Input/types.ts, packages/components/src/RangeInput/components/Track/index.tsx, packages/components/src/RangeInput/components/Track/styles.ts, packages/components/src/RangeInput/index.tsx, packages/components/src/RangeInput/styles.ts, packages/components/src/RangeInput/types.ts
=> V3: add option to control styles for RangeInput

packages/search-ui/src/ContextProvider/types.ts, packages/search-ui/src/Filter/Box.tsx, packages/search-ui/src/Filter/ColorFilter.tsx, packages/search-ui/src/Filter/Header.tsx, packages/search-ui/src/Filter/ListFilter.tsx, packages/search-ui/src/Filter/RatingFilter.tsx, packages/search-ui/src/Filter/TabFilter.tsx
Add options to control styles for Filter component:
=> feat: add option to control styles for Filter

packages/components/src/Rating/styles.ts, packages/components/src/Rating/test/Rating.test.tsx, packages/components/src/Rating/types.ts, packages/components/src/utils/rating.ts, packages/components/src/utils/test/rating.test.ts
=> V3: add test for rating

packages/components/src/Button/test/Button.test.tsx, packages/components/src/Button/test/__snapshots__/Button.test.tsx.snap, packages/components/src/ButtonGroup/test/ButtonGroup.test.tsx, packages/components/src/ButtonGroup/test/__snapshots__/ButtonGroup.test.tsx.snap, packages/components/src/Checkbox/test/Checkbox.test.tsx, packages/components/src/Pagination/test/Pagination.test.tsx, packages/components/src/Radio/test/Radio.test.tsx, packages/components/src/Swatch/test/Swatch.test.tsx, packages/components/src/Tabs/test/Tabs.test.tsx, packages/components/src/test/utils.tsx
=> Add test for button group

docs/pages/search-ui/index.mdx, packages/search-ui/package.json, packages/search-ui/src/Filter/Box.tsx, packages/search-ui/src/Filter/ListFilter.tsx, yarn.lock
=> V3: fix laggy filter search

docs/pages/search-ui/filter.mdx, packages/hooks/src/ContextProvider/index.tsx, packages/hooks/src/ContextProvider/types.ts, packages/search-ui/src/ContextProvider/index.tsx
Subject to change after the requirements are made clear.
=> V3: WIP - add default filter

.changeset/three-countries-push.md, packages/search-ui/src/Filter/ListFilter.tsx, yarn.lock
Not sure if there's a term for this kind of bug and whether I'm handling it the right way though.
=> fix: list filter item has wrong focus

.changeset/funny-timers-repeat.md, packages/search-ui/src/Summary/index.tsx, packages/search-ui/src/i18n/locale/en.ts
Fix the issue raised in https://sajari.atlassian.net/browse/SF-252.
=> fix: wrong summary message when query is disabled

.changeset/chatty-pears-serve.md, packages/hooks/src/ContextProvider/index.tsx
=> fix: set searching state when calling pagination

.changeset/cyan-seahorses-turn.md, packages/components/src/Rating/types.ts
Resolves https://sajari.atlassian.net/browse/SF-297
=> fix: add descriptive error for rating

.changeset/fluffy-peaches-pump.md, packages/hooks/src/ContextProvider/controllers/filters/RangeFilterBuilder.ts, packages/hooks/src/ContextProvider/controllers/filters/test/RangeFilterBuilder.test.ts, packages/hooks/src/ContextProvider/index.tsx, packages/hooks/src/ContextProvider/types.ts, packages/hooks/src/useSearchContext/index.ts
This reverts commit a610c50aefef1b751c4243421fcbd179014f97d8.
=> Revert "feat: support reset all filters (#460)"

.changeset/rotten-fireants-refuse.md, packages/search-ui/src/Filter/ListFilter.tsx
Fix a bug that causes the document's editor to not working
=> fix: document focus element

.changeset/cyan-pans-hug.md, packages/search-ui/src/utils/test/mapResultFields.test.ts
Add test cases to cover array field inputs for `mapResultFields`.
=> test: add test cases for mapResultFields

.changeset/neat-numbers-begin.md, packages/hooks/src/ContextProvider/controllers/Variables.ts, packages/hooks/src/ContextProvider/controllers/index.ts, packages/hooks/src/ContextProvider/index.tsx, packages/hooks/src/index.ts
Fix missing type exports in Variables.
=> fix: missing type exports in Variables

.changeset/fresh-owls-clean.md, packages/hooks/src/ContextProvider/controllers/Pipeline.ts
=> chore: code quality in response to missed code review comment.

.changeset/thin-years-drive.md, packages/components/src/Modal/styles.ts, packages/components/src/Modal/types.ts, packages/search-ui/src/Input/types.ts
feat: overlay z index and focus
=> feat: overlay z index and focus

.changeset/real-seahorses-prove.md, packages/hooks/package.json, packages/hooks/src/useTracking/index.ts, packages/hooks/src/useTracking/types.ts, packages/search-ui/src/Results/components/Result/index.tsx, packages/search-ui/src/Results/components/Result/types.ts, packages/search-ui/src/Results/index.tsx, packages/search-ui/src/hooks/index.ts, packages/search-ui/src/hooks/useClickTracking.ts, packages/search-ui/src/hooks/usePosNegTracking.ts, yarn.lock
Check this one second 2️⃣
The other two PRs that make up this end-to-end change are:
- sdk-js https://github.com/sajari/sdk-js/pull/117
- search-widgets https://github.com/sajari/search-widgets/pull/159
=> feat: implement shopify compatible pos neg tracking in Result component

.changeset/fluffy-ads-pump.md, docs/pages/search-ui/results.mdx, packages/search-ui/src/Results/components/Result/index.tsx, packages/search-ui/src/Results/components/Result/types.ts, packages/search-ui/src/Results/index.tsx, packages/search-ui/src/Results/types.ts
Resolve https://github.com/sajari/sdk-react/issues/615
=> feat: allow result links to be open in a new tab

.changeset/spicy-cats-happen.md, packages/utils/src/assertion.ts
chore: try again for IE11 support
=> chore: try again for IE11 support

.changeset/fair-crabs-decide.md, packages/hooks/package.json
chore: bumped version of utils used by hooks
=> chore: bumped version of utils used by hooks

.changeset/spotty-ants-leave.md, packages/search-ui/src/Results/components/Result/index.tsx, packages/search-ui/src/Results/components/TemplateResult/index.tsx
feat: handle right and middle click in result tracking
=> feat: handle right and middle click in result tracking

.changeset/khaki-islands-help.md, docs/components/menu-items.ts, docs/pages/hooks/usetracking.mdx, docs/pages/tracking/advanced.mdx, docs/pages/tracking/index.mdx
feat: documentation for new hook features and advanced tracking use-cases
=> feat: documentation for new hook features and advanced tracking use-cases

.changeset/strong-socks-refuse.md, docs/pages/classes/posneglocalstoragemanager.mdx, docs/pages/hooks/usetracking.mdx, docs/pages/tracking/advanced.mdx
chore: docs example code syntax errors cleanup, link fixes and minor clarifications
=> chore: docs example code syntax errors cleanup, link fixes and minor clarifications

.changeset/tame-grapes-roll.md, docs/pages/components/modal.mdx
chore: document z-index setting on modal
=> chore: document z-index setting on modal

package.json, yarn.lock
chore: bump can i use database
=> chore: bump can i use database

.changeset/heavy-pianos-drop.md, packages/hooks/src/useFilter/index.ts, packages/hooks/src/useFilter/test/utils.test.ts, packages/hooks/src/useFilter/utils.ts
perf: improved performance of useFilter to account for large option data sets
=> perf: improved performance of useFilter to account for large option data sets

packages/hooks/package.json, packages/hooks/src/ContextProvider/controllers/Response.ts, packages/hooks/src/ContextProvider/index.tsx, packages/hooks/src/ContextProvider/types.ts, packages/hooks/src/useAutocomplete/index.ts, packages/hooks/src/useSearch/index.ts, packages/hooks/src/useSearch/types.ts, yarn.lock
chore: import redirects type and fix up introduced type errors.
=> chore: import redirects type and fix up introduced type errors.

.changeset/tasty-suits-mate.md
feat: implement redirects across all relevant components
=> feat: implement redirects across all relevant components

.changeset/old-peas-rest.md, packages/hooks/package.json, packages/hooks/src/ContextProvider/controllers/Response.ts, yarn.lock
feat: better handling of redirects
=> feat: better handling of redirects

.changeset/early-pumpkins-worry.md, packages/components/src/Select/index.tsx
perf: performance improvement to select component
=> perf: performance improvement to select component

.changeset/sixty-doors-drum.md, packages/components/src/Combobox/index.tsx, packages/search-ui/src/Input/index.tsx
feat: redirects are now implemented in search-ui package
Won't push this out until mid next week to avoid problems with major shopping days in some locales.
=> feat: redirects are now implemented in search-ui package

.changeset/clever-dryers-hammer.md, docs/pages/search-ui/input.mdx
docs: documentation example for redirects
=> docs: documentation example for redirects

.changeset/good-buttons-act.md, docs/components/Navigation/SideNav/index.tsx
bug: remove extraneous item from docs sidebar
=> bug: remove extraneous item from docs sidebar

.changeset/hot-bugs-exist.md, docs/pages/hooks/usesearch.mdx, packages/hooks/package.json, packages/hooks/src/ContextProvider/controllers/Response.ts, packages/hooks/src/useSearch/index.ts, packages/hooks/src/useSearch/types.ts, packages/hooks/src/useSearchContext/index.ts, packages/search-ui/CHANGELOG.md, yarn.lock
https://search-io.atlassian.net/browse/SF-695
=> feat: integrate banners to useSearch

.changeset/poor-buttons-collect.md, packages/search-ui/src/Results/components/BannerItem/index.tsx, packages/search-ui/src/Results/components/BannerItem/styles.ts, packages/search-ui/src/Results/index.test.tsx
The banner image container is having absolute position style so when there is only a banner on a row it will collapse to zero height because no other result item is there to establish the height.
Only apply the absolute style when the column span of that banner is larger than the total number of columns.
=> fix: banner absolute position

.changeset/thirty-bottles-shake.md, packages/components/src/RangeInput/index.tsx
Add data-tesid for range filter input so that it can be queried for testing
=> fix: add data-testid for range filter track

.changeset/calm-gorillas-compete.md, packages/search-ui/src/i18n/locale/de.ts, packages/search-ui/src/i18n/locale/en.ts, packages/search-ui/src/i18n/locale/es.ts, packages/search-ui/src/i18n/locale/fr.ts, packages/search-ui/src/i18n/locale/it.ts, packages/search-ui/src/i18n/locale/nl.ts, packages/search-ui/src/i18n/types.ts
- Add translation for "Toggle Filters"
=> feat: add translation for Toggle Filters text

.changeset/four-deers-bake.md, packages/hooks/src/ContextProvider/index.tsx, packages/hooks/src/utils/queryParams.ts, packages/search-ui/src/ContextProvider/index.tsx, packages/search-ui/src/utils/queryParams.ts, packages/utils/src/index.ts, packages/utils/src/search-params.ts
Fix incorrect intial value of viewType as it should respect the value from URL param
=> fix: incorrect init value of viewType

.changeset/breezy-tigers-cough.md, packages/hooks/src/ContextProvider/index.tsx, packages/hooks/src/URLStateSync/index.tsx, packages/hooks/src/usePagination/index.ts
- Add the page param to the list of watchers
https://search-io.atlassian.net/browse/SF-865
=> feat: add page param to StateSyncURL component

.changeset/brave-beans-drum.md, packages/search-ui/src/i18n/locale/de.ts, packages/search-ui/src/i18n/locale/en.ts, packages/search-ui/src/i18n/locale/es.ts, packages/search-ui/src/i18n/locale/fr.ts, packages/search-ui/src/i18n/locale/it.ts, packages/search-ui/src/i18n/locale/nl.ts, packages/search-ui/src/i18n/types.ts
https://search-io.atlassian.net/browse/SF-877
=> fix: wrong french translation

.changeset/sharp-turkeys-wash.md, packages/components/src/Combobox/index.tsx
bug: fix problem with input on mobile not changing input value when item is selected
=> bug: fix problem with input on mobile not changing input value when item is selected

.changeset/three-wombats-unite.md, packages/components/src/Combobox/components/DropdownItem/index.tsx, packages/components/src/Combobox/index.tsx
fix: another attempt at fixing input takeover not setting input value on mobile
[SF-906](https://search-io.atlassian.net/browse/SF-906)
=> fix: another attempt at fixing input takeover not setting input value on mobile

docs/pages/hooks/searchprovider.mdx
Update the missing docs of https://github.com/sajari/sdk-react/pull/824
=> docs: add paramKeys docs

.changeset/purple-elephants-refuse.md, packages/search-ui/src/i18n/locale/fr.ts
=> fix: improve French translations

.changeset/tiny-vans-serve.md, packages/search-ui/src/Filter/ColorFilter.tsx, packages/search-ui/src/Filter/ListFilter.tsx, packages/search-ui/src/Filter/SelectFilter.tsx, packages/search-ui/src/Filter/TabFilter.tsx
https://search-io.atlassian.net/browse/SF-936
=> bug: a filter with a single option which is selected should not be hidden

.changeset/many-singers-act.md, packages/search-ui/src/i18n/locale/fr.ts
[SF-942](https://search-io.atlassian.net/browse/SF-942)
=> fix: improve french translations for sort and no results msg

.changeset/spotty-bananas-heal.md, yarn.lock
[SF-972](https://search-io.atlassian.net/browse/SF-972)
=> chore(deps): bump dset

.changeset/tough-rabbits-fold.md, .eslintrc, docs/pages/search-ui/input.mdx, packages/search-ui/src/Input/index.test.tsx, packages/search-ui/src/Input/index.tsx, packages/search-ui/src/Input/utils/index.test.ts, packages/search-ui/src/Input/utils/index.ts
Reverts #877.
Take 2 of #875.
[DAU-249](https://algolia.atlassian.net/browse/DAU-249)
=> feat: make redirects via the input component case-insensitive
